dbt_bq_project:
  outputs:
    dev:
      dataset: sales_dataset_bq_dbt
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/kurinchiban/Desktop/dbt-bigquery/sa_key.json
      location: us-central1
      method: service-account
      priority: interactive
      project: stoked-brand-474706-u8
      threads: 1
      type: bigquery

    prod:
      dataset: sales_dataset_bq_dbt_prod         
      job_execution_timeout_seconds: 400         
      job_retries: 1                             
      keyfile: /home/kurinchiban/Desktop/dbt-bigquery/sa_key.json
      location: us-central1
      method: service-account
      priority: interactive                           
      project: stoked-brand-474706-u8      
      threads: 1                                 
      type: bigquery

  target: dev